# Generated by Django 5.2.5 on 2025-09-03 18:13

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "😢 Очень плохое"),
                            (2, "😞 Плохое"),
                            (3, "😐 Нейтральное"),
                            (4, "🙂 Хорошее"),
                            (5, "😊 Отличное"),
                        ],
                        verbose_name="Уровень настроения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настроение",
                "verbose_name_plural": "Настроения",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "Тег должен быть не короче 2 символов"
                            )
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        choices=[
                            ("#6aa958", "Зеленый"),
                            ("#ca1d23", "Красный"),
                            ("#003d92", "Синий"),
                            ("#72757a", "Серый"),
                            ("#e7949e", "Розовый"),
                        ],
                        default="#FFFFFF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Для стандартных тегов владелец не указан",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "Заголовок должен быть не короче 3 символов"
                            )
                        ],
                        verbose_name="Заголовок",
                    ),
                ),
                ("content", markdownx.models.MarkdownxField(verbose_name="Содержание")),
                (
                    "content_html",
                    models.TextField(editable=False, verbose_name="HTML содержимое"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "entry_date",
                    models.DateField(
                        help_text="Дата, к которой относится запись",
                        verbose_name="Дата записи",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "mood",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diary.mood",
                        verbose_name="Настроение",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="diary.tag", verbose_name="Теги"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["-entry_date", "-date_created"],
            },
        ),
    ]
