# Generated by Django 5.2.5 on 2025-09-10 19:27

import colorfield.fields
import django.core.validators
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "Заголовок должен быть не короче 3 символов"
                            )
                        ],
                        verbose_name="Заголовок",
                    ),
                ),
                ("content", markdownx.models.MarkdownxField(verbose_name="Содержание")),
                (
                    "content_html",
                    models.TextField(editable=False, verbose_name="HTML содержимое"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "entry_date",
                    models.DateField(
                        help_text="Дата, к которой относится запись",
                        verbose_name="Дата записи",
                    ),
                ),
                (
                    "mood",
                    models.IntegerField(
                        choices=[
                            (1, "😢 Очень плохое"),
                            (2, "😞 Плохое"),
                            (3, "😐 Нейтральное"),
                            (4, "🙂 Хорошее"),
                            (5, "😊 Отличное"),
                        ],
                        default=5,
                        verbose_name="Уровень настроения",
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество слов"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "Тег должен быть не короче 2 символов"
                            )
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#e7949e",
                        image_field=None,
                        max_length=25,
                        samples=(
                            ("#6aa958", "Зеленый"),
                            ("#ca1d23", "Красный"),
                            ("#003d92", "Синий"),
                            ("#72757a", "Серый"),
                            ("#e7949e", "Розовый"),
                        ),
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
    ]
