# Generated by Django 5.2.5 on 2025-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="word_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество слов"
            ),
        ),
    ]
