# Generated by Django 5.2.5 on 2025-09-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="mood",
            field=models.IntegerField(
                choices=[
                    (1, "😢 Очень плохое"),
                    (2, "😞 Плохое"),
                    (3, "😐 Нейтральное"),
                    (4, "🙂 Хорошее"),
                    (5, "😊 Отличное"),
                ],
                default=5,
                verbose_name="Уровень настроения",
            ),
        ),
        migrations.DeleteModel(
            name="Mood",
        ),
    ]
