# Generated by Django 5.2.5 on 2025-09-04 20:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_alter_entry_mood_delete_mood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                samples=(
                    ("#6aa958", "Зеленый"),
                    ("#ca1d23", "Красный"),
                    ("#003d92", "Синий"),
                    ("#72757a", "Серый"),
                    ("#e7949e", "Розовый"),
                ),
            ),
        ),
    ]
