# Generated by Django 5.2.5 on 2025-09-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_entry_word_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name": "Запись", "verbose_name_plural": "Записи"},
        ),
    ]
